name: "01 event repository dispatch" 
on:
    repository_dispatch:
        types: [say_hi_event]
jobs:
    say-hi:
        runs-on: ubuntu-latest
        steps:
            - name: say hi
              run: echo "Hola ${{github.event.client_payload.name}}"
